# Generated by Django 6.0.2 on 2026-06-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('area_of_interest', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('consent_communications', models.BooleanField(default=False)),
                ('consent_privacy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('rss_url', models.URLField(blank=True, null=True)),
                ('atom_url', models.URLField(blank=True, null=True)),
                ('careers_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('blog_url', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_employer_name')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('years', models.PositiveIntegerField(default=0, help_text='Minimum years of experience required')),
                ('location', models.CharField(max_length=100, null=True)),
                ('mode', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('idx', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joblinx.employer')),
            ],
        ),
    ]
