# Generated by Django 6.0.2 on 2026-06-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
