# Generated by Django 6.0.2 on 2026-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0002_job_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
