# Generated by Django 6.0.2 on 2026-06-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0002_job_is_active_job_location_job_salary_job_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
