# Generated by Django 6.0.2 on 2026-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0003_job_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
