# Generated by Django 6.0.2 on 2026-06-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0003_job_seniority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='seniority',
            new_name='experience_level',
        ),
    ]
