# Generated by Django 6.0.2 on 2026-06-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0004_rename_seniority_job_experience_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience_level',
            new_name='seniority',
        ),
    ]
