# Generated by Django 6.0.2 on 2026-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0004_job_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('area_of_interest', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('consent_communications', models.BooleanField(default=False)),
                ('consent_privacy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
