# Generated by Django 6.0.2 on 2026-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0005_talentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
