# Generated by Django 6.0.2 on 2026-06-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0006_job_posted_date_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Minimum years of experience required'),
        ),
        migrations.AlterField(
            model_name='job',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
