# Generated by Django 6.0.2 on 2026-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0006_sourcestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcestate',
            name='last_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
