# Generated by Django 6.0.2 on 2026-06-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0007_job_years_experience_alter_job_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='years_experience',
            new_name='years',
        ),
    ]
