# Generated by Django 6.0.2 on 2026-06-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0007_sourcestate_last_status'),
        ('joblinx', '0008_rename_years_experience_job_years'),
    ]

    operations = [
    ]
