# Generated by Django 6.0.2 on 2026-06-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0009_merge_20260620_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AlterField(
            model_name='talentsubmission',
            name='area_of_interest',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='talentsubmission',
            name='experience_level',
            field=models.CharField(max_length=100),
        ),
    ]
