# Generated by Django 6.0.2 on 2026-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblinx', '0010_remove_job_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='why',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
